### ISSUE TITLE
Milestone 1 : Kanban  board setup

### ISSUE THREAD

**Issue by Nemwel-Boniface** [Nemwel-Boniface/let-sChill#21]
## Open-source Library

The Projects link is [this](https://github.com/Nemwel-Boniface/openSourceLibrary/projects/1) one. We are a group of two 
- [Nemwel](https://github.com/Nemwel-Boniface)
- [Zelalem](https://github.com/zmekonnen251)

## Hello reviewer(s) :wave: :wave: 

Thank you for taking the time to review our project setup.

**Comment by elmar8287** [comment]
Hi, team.

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
